version: "3.3"

services:
  api:
    image: index.docker.io/edwinjoseph/example-chatapp_api:latest
    ports:
      - 5000:5000
    
  client:
    image: index.docker.io/edwinjoseph/example-chatapp_web:latest
    volumes:
      - ./services/web:/web
      - /web/node_modules
      - /web/.next
    depends_on:
      - api
    ports:
      - 8080:8080
