name: Build containers for prod & push to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-api:
    name: Build and deploy API
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: ./services/api/Dockerfile
        tags: edwinjoseph/example-chatapp_api:latest
        push: true

  build-and-deploy-web:
    name: Build and deploy web
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: ./services/web/Dockerfile
        tags: edwinjoseph/example-chatapp_web:latest
        push: true